---
- name: Despliegue Profesional IoT con Control Total en Portainer
  hosts: localhost
  vars:
    repo_url: "https://github.com/fran-garrido/iot-stack-docker.git"
    base_path: "/opt/iot-stack"
    user_name: "{{ ansible_user_id }}"
    influx_token_file: "{{ base_path }}/.env"
    portainer_user: "vdc"
    portainer_password: "vdc_IoT2026!"

  tasks:
    - name: 1. Instalar dependencias del sistema
      apt:
        update_cache: yes
        name: [git, curl, python3-pip, python3-docker, cockpit, openssl]

    - name: 2. Activar Cockpit
      systemd:
        name: cockpit.socket
        state: started
        enabled: yes

    - name: 3. Instalar Docker
      shell: curl -fsSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker

    - name: 4. Crear directorio base
      file:
        path: "{{ base_path }}"
        state: directory
        owner: "{{ user_name }}"
        group: docker
        mode: '0775'

    - name: 5. Clonar repositorio
      git:
        repo: "{{ repo_url }}"
        dest: "{{ base_path }}"
        force: yes

    - name: 6. Crear estructura de subcarpetas de datos
      file:
        path: "{{ base_path }}/{{ item }}"
        state: directory
        owner: "{{ user_name }}"
        group: docker
        mode: '0775'
      with_items:
        - mosquitto/config
        - mosquitto/data
        - mosquitto/log
        - influxdb/data
        - influxdb/config
        - grafana/data
        - telegraf

    - name: 7. Generar Token de InfluxDB
      shell: "openssl rand -hex 32"
      register: generated_token
      args:
        creates: "{{ influx_token_file }}"

    - name: 8. Crear archivo .env
      copy:
        dest: "{{ influx_token_file }}"
        content: |
          INFLUXDB_TOKEN={{ generated_token.stdout | default('already_exists') }}
          UID={{ ansible_user_uid }}
          GID={{ ansible_user_gid }}
        force: no

    - name: 9. Limpiar contenedores previos (Evitar conflictos)
      docker_container:
        name: "{{ item }}"
        state: absent
      with_items: [mosquitto, influxdb, telegraf, grafana]

    - name: 10. Desplegar Contenedor de Portainer
      docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        state: started
        restart_policy: always
        published_ports:
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data

    - name: 11. Esperar e Inicializar Administrador de Portainer (vdc)
      uri:
        url: https://localhost:9443/api/users/admin/init
        method: POST
        body_format: json
        body:
          username: "{{ portainer_user }}"
          password: "{{ portainer_password }}"
        validate_certs: no
        status_code: [200, 409, 412]
      register: portainer_init
      until: portainer_init.status in [200, 409, 412]
      retries: 15
      delay: 5

    - name: 12. Obtener Token de la API de Portainer
      uri:
        url: https://localhost:9443/api/auth
        method: POST
        body_format: json
        body:
          username: "{{ portainer_user }}"
          password: "{{ portainer_password }}"
        validate_certs: no
      register: portainer_auth

    - name: 13. Obtener el ID del entorno (Endpoint)
      uri:
        url: https://localhost:9443/api/endpoints
        method: GET
        headers:
          Authorization: "Bearer {{ portainer_auth.json.jwt }}"
        validate_certs: no
      register: portainer_endpoints
      until: portainer_endpoints.json | length > 0
      retries: 10
      delay: 5

    - name: 14. Desplegar Stack en Portainer (Control Total)
      uri:
        url: "https://localhost:9443/api/stacks/create/standalone/repository?endpointId={{ portainer_endpoints.json[0].Id }}"
        method: POST
        headers:
          Authorization: "Bearer {{ portainer_auth.json.jwt }}"
        body_format: json
        body:
          name: "iot-infrastructure"
          repositoryURL: "{{ repo_url }}"
          composeFormat: "compose-v2"
          repositoryAuthentication: false
          ComposeFilePathInRepository: "docker-compose.yml"
        validate_certs: no
        status_code: [200, 409]
