---
- name: Despliegue Portable IoT (Ansible + Portainer)
  hosts: localhost
  vars:
    repo_url: "https://github.com/fran-garrido/iot-stack-docker.git"
    base_path: "/opt/iot-stack"
    user_name: "{{ ansible_user_id }}"
    influx_token_file: "{{ base_path }}/.env"    
    portainer_user: "admin"
    portainer_password: "vdc_IoT2026!"

  tasks:
    - name: 1. Instalar dependencias base
      apt:
        update_cache: yes
        name: [git, curl, python3-pip, python3-docker, cockpit, openssl]

    - name: 2. Instalar Docker Engine (Script Oficial)
      shell: curl -fsSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker

    - name: 3. Asegurar que Docker esté iniciado y habilitado
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: 4. Garantizar que el grupo docker existe
      group:
        name: docker
        state: present

    - name: 5. Añadir usuario al grupo docker
      user:
        name: "{{ user_name }}"
        groups: docker
        append: yes

    - name: 6. Asegurar directorio de trabajo
      file:
        path: "{{ base_path }}"
        state: directory
        owner: "{{ user_name }}"
        group: docker
        mode: '0775'

    - name: 7. Sincronizar archivos del repositorio a /opt/iot-stack
      copy:
        src: "./"
        dest: "{{ base_path }}"
        owner: "{{ user_name }}"
        group: docker
        mode: '0775'

    - name: 8. Generar Token único de InfluxDB
      shell: "openssl rand -hex 32"
      register: generated_token
      args:
        creates: "{{ influx_token_file }}"

    - name: 9. Crear archivo .env local
      copy:
        dest: "{{ influx_token_file }}"
        content: |
          INFLUXDB_TOKEN={{ generated_token.stdout | default('TOKEN_EXISTENTE') }}
          UID={{ ansible_user_uid }}
          GID={{ ansible_user_gid }}
        force: no

    - name: 10. Desplegar Portainer (Puerto 9443)
      docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        state: started
        restart_policy: always
        published_ports: ["9443:9443"]
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data

    - name: 11. Inicializar usuario admin en Portainer
      uri:
        url: https://localhost:9443/api/users/admin/init
        method: POST
        body_format: json
        body:
          username: "{{ portainer_user }}"
          password: "{{ portainer_password }}"
        validate_certs: no
        status_code: [200, 409, 412]
      register: portainer_init
      until: portainer_init.status in [200, 409, 412]
      retries: 15
      delay: 5

    - name: 12. Obtener Token y lista de entornos (Endpoints)
      uri:
        url: https://localhost:9443/api/auth
        method: POST
        body: { "username": "{{ portainer_user }}", "password": "{{ portainer_password }}" }
        body_format: json
        validate_certs: no
      register: portainer_auth

    - name: 12.5 Consultar ID del entorno dinámicamente
      uri:
        url: https://localhost:9443/api/endpoints
        method: GET
        headers:
          Authorization: "Bearer {{ portainer_auth.json.jwt }}"
        validate_certs: no
      register: portainer_endpoints
      until: portainer_endpoints.json | length > 0
      retries: 10
      delay: 5

    - name: 13. Desplegar Stack desde GitHub (Control Total)
      uri:
        url: "https://localhost:9443/api/stacks/create/standalone/repository?endpointId={{ portainer_endpoints.json[0].Id }}"
        method: POST
        headers: { "Authorization": "Bearer {{ portainer_auth.json.jwt }}" }
        body_format: json
        body:
          name: "iot-stack"
          repositoryURL: "{{ repo_url }}"
          composeFormat: "compose-v2"
          ComposeFilePathInRepository: "docker-compose.yml"
        validate_certs: no
        status_code: [200, 409]
