---
- name: Despliegue Portable IoT - Versión Aula (todo dentro del proyecto)
  hosts: localhost
  vars:
    repo_url: "https://github.com/fran-garrido/iot-stack-docker.git"
    portainer_user: "admin"
    portainer_password: "vdc_IoT2026!"

  tasks:
    - name: 1. Instalar dependencias mínimas
      apt:
        update_cache: yes
        name: [git, curl, python3-pip, python3-docker, openssl]
        state: present

    - name: 2. Instalar Docker (script oficial)
      shell: curl -fsSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker

    - name: 3. Asegurar Docker iniciado y habilitado
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: 4. Asegurar grupo docker
      group:
        name: docker
        state: present

    - name: 5. Añadir usuario actual al grupo docker
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: 6. Generar token InfluxDB si no existe .env
      shell: "openssl rand -hex 32"
      register: generated_token
      args:
        creates: "{{ playbook_dir }}/.env"

    - name: 7. Crear .env si no existe
      copy:
        dest: "{{ playbook_dir }}/.env"
        content: |
          INFLUXDB_TOKEN={{ generated_token.stdout }}
          UID={{ ansible_user_uid }}
          GID={{ ansible_user_gid }}
        mode: '0664'
        force: no

    - name: 8. Desplegar Portainer (HTTPS 9443)
      docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        state: started
        restart_policy: always
        published_ports: ["9443:9443"]
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data

    - name: 9. Inicializar usuario admin en Portainer
      uri:
        url: https://localhost:9443/api/users/admin/init
        method: POST
        body_format: json
        body:
          username: "{{ portainer_user }}"
          password: "{{ portainer_password }}"
        validate_certs: no
        status_code: [200, 409, 412]
      register: portainer_init
      until: portainer_init.status in [200, 409, 412]
      retries: 15
      delay: 5

    - name: 10. Obtener token API Portainer
      uri:
        url: https://localhost:9443/api/auth
        method: POST
        body_format: json
        body:
          username: "{{ portainer_user }}"
          password: "{{ portainer_password }}"
        validate_certs: no
      register: portainer_auth

    - name: 11. Crear endpoint local si no existe
      uri:
        url: "https://localhost:9443/api/endpoints"
        method: POST
        headers:
          Authorization: "Bearer {{ portainer_auth.json.jwt }}"
        body_format: form-multipart
        body:
          Name: "local"
          EndpointCreationType: "1"
        validate_certs: no
        status_code: [200, 409]
      ignore_errors: yes

    - name: 12. Pequeña espera
      pause:
        seconds: 8

    - name: 13. Leer docker-compose.yml
      slurp:
        src: "{{ playbook_dir }}/docker-compose.yml"
      register: compose_content

    - name: 14. Pre-descargar imágenes (opcional - mejora UX)
      shell: "docker pull {{ item }}"
      loop:
        - eclipse-mosquitto:2.0
        - influxdb:2.7
        - telegraf:1.32
        - grafana/grafana:11.3.0
        - nodered/node-red:latest
      ignore_errors: yes

    - name: 15. Crear stack en Portainer
      uri:
        url: "https://localhost:9443/api/stacks/create/standalone/string?endpointId={{ portainer_endpoints.json[0].Id | default('1') }}"
        method: POST
        headers:
          Authorization: "Bearer {{ portainer_auth.json.jwt }}"
        body_format: json
        body:
          name: "iot-aula"
          stackFileContent: "{{ compose_content.content | b64decode }}"
          env:
            - name: "INFLUXDB_TOKEN"
              value: "{{ lookup('file', playbook_dir + '/.env') | regex_search('INFLUXDB_TOKEN=(.+)', '\\1') | first }}"
            - name: "UID"
              value: "{{ ansible_user_uid }}"
            - name: "GID"
              value: "{{ ansible_user_gid }}"
        validate_certs: no
        status_code: [200, 409]
      register: stack_result

    - name: 16. Resumen final
      debug:
        msg: 
          - "¡INSTALACIÓN FINALIZADA!"
          - "Portainer → https://localhost:9443"
