---
- name: Despliegue Portable IoT (Ansible + Portainer)
  hosts: localhost
  vars:
    repo_url: "https://github.com/fran-garrido/iot-stack-docker.git"
    base_path: "/opt/iot-stack"
    user_name: "{{ ansible_user_id }}"
    influx_token_file: "{{ base_path }}/.env"    
    portainer_user: "admin"
    portainer_password: "vdc_IoT2026!"

  tasks:
    - name: 1. Instalar dependencias base
      apt:
        update_cache: yes
        name: [git, curl, python3-pip, python3-docker, cockpit, openssl]

    - name: 2. Instalar Docker Engine (Script Oficial)
      shell: curl -fsSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker

    - name: 3. Asegurar que Docker esté iniciado y habilitado
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: 4. Garantizar que el grupo docker existe
      group:
        name: docker
        state: present

    - name: 5. Añadir usuario al grupo docker
      user:
        name: "{{ user_name }}"
        groups: docker
        append: yes

    - name: 6. Asegurar directorio de trabajo
      file:
        path: "{{ base_path }}"
        state: directory
        owner: "{{ user_name }}"
        group: docker
        mode: '0775'

    - name: 7. Sincronizar archivos del repositorio a /opt/iot-stack
      copy:
        src: "./"
        dest: "{{ base_path }}"
        owner: "{{ user_name }}"
        group: docker
        mode: '0775'

    - name: 8. Generar Token único de InfluxDB
      shell: "openssl rand -hex 32"
      register: generated_token
      args:
        creates: "{{ influx_token_file }}"

    - name: 9. Crear archivo .env local
      copy:
        dest: "{{ influx_token_file }}"
        content: |
          INFLUXDB_TOKEN={{ generated_token.stdout | default('TOKEN_EXISTENTE') }}
          UID={{ ansible_user_uid }}
          GID={{ ansible_user_gid }}
        force: no

    - name: 10. Desplegar Portainer (Puerto 9443)
      docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        state: started
        restart_policy: always
        published_ports: ["9443:9443"]
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data

    - name: 11. Inicializar usuario admin en Portainer
      uri:
        url: https://localhost:9443/api/users/admin/init
        method: POST
        body_format: json
        body:
          username: "{{ portainer_user }}"
          password: "{{ portainer_password }}"
        validate_certs: no
        status_code: [200, 409, 412]
      register: portainer_init
      until: portainer_init.status in [200, 409, 412]
      retries: 15
      delay: 5

    - name: 12. Obtener Token de la API de Portainer
      uri:
        url: https://localhost:9443/api/auth
        method: POST
        body_format: json
        body:
          username: "{{ portainer_user }}"
          password: "{{ portainer_password }}"
        validate_certs: no
      register: portainer_auth

    - name: 13. Crear endpoint local si no existe (form-multipart correcto)
      uri:
        url: "https://localhost:9443/api/endpoints"
        method: POST
        headers:
          Authorization: "Bearer {{ portainer_auth.json.jwt }}"
        body_format: form-multipart
        body:
          Name: "local-docker"                  # Nombre sin espacios ni caracteres raros, prueba también "Local" o "primary"
          EndpointCreationType: "1"             # 1 = entorno Docker local
          # URL: "unix:///var/run/docker.sock"  # ← OPCIONAL, en la mayoría de versiones recientes NO lo pongas para local
        validate_certs: no
        status_code: [200, 409]                 # 409 = ya existe → lo ignoramos
      register: create_endpoint
      changed_when: create_endpoint.status == 200
      ignore_errors: yes   # Quita esto después de probar, solo para debug inicial

    - name: 14. Pequeña espera para que Portainer registre el endpoint
      pause:
        seconds: 8

    - name: 15. Obtener lista de endpoints (ahora debería haber al menos 1)
      uri:
        url: "https://localhost:9443/api/endpoints"
        method: GET
        headers:
          Authorization: "Bearer {{ portainer_auth.json.jwt }}"
        validate_certs: no
      register: portainer_endpoints
      until: portainer_endpoints.json | length > 0 and portainer_endpoints.json[0].Id is defined
      retries: 12
      delay: 5

    - name: 16. Leer el contenido del docker-compose.yml local
      slurp:
        src: "{{ playbook_dir }}/docker-compose.yml"
      register: compose_content

    - name: 16.5 Pre-descargar imágenes (Para ver el progreso)
      shell: "docker pull {{ item }}"
      loop:
        - "eclipse-mosquitto:latest"
        - "influxdb:2.7"
        - "telegraf:latest"
        - "grafana/grafana:latest"
        - "nodered/node-red:latest
      timeout: 300
      register: pull_result
      changed_when: "'Downloaded newer image' in pull_result.stdout"

    - name: 17. Desplegar Stack en Portainer usando el archivo local
      uri:
        url: "https://localhost:9443/api/stacks/create/standalone/string?endpointId={{ portainer_endpoints.json[0].Id }}"
        method: POST
        headers:
          Authorization: "Bearer {{ portainer_auth.json.jwt }}"
        body_format: json
        body:
          name: "iot-infrastructure"
          stackFileContent: "{{ compose_content.content | b64decode }}"
          env:
            - name: "INFLUXDB_TOKEN"
              value: "{{ generated_token.stdout | string }}"
            - name: "UID"
              value: "{{ ansible_user_uid | string }}"
            - name: "GID"
              value: "{{ ansible_user_gid | string }}"
        validate_certs: no
        status_code: [200, 409]
        timeout: 60 
      register: stack_deployment

    - name: 18. Verificar contenedores activos
      shell: "docker ps --format '{{ '{{' }}.Names{{ '}}' }}: {{ '{{' }}.Status{{ '}}' }}'"
      register: docker_status
      changed_when: false

    - name: 19. Resumen del Sistema
      debug:
        msg: 
          - "INSTALACIÓN COMPLETADA CON ÉXITO"
          - "--------------------------------"
          - "{{ docker_status.stdout_lines }}"
          - "--------------------------------"
          - "Portainer: https://{{ ansible_host | default('localhost') }}:9443"
