---
- name: Despliegue Portable IoT (Ansible + Portainer)
  hosts: localhost
  vars:
    repo_url: "https://github.com/fran-garrido/iot-stack-docker.git"
    base_path: "/opt/iot-stack"
    user_name: "{{ ansible_user_id }}"
    influx_token_file: "{{ base_path }}/.env"
    portainer_user: "vdc"
    portainer_password: "vdc_IoT2026!"

  tasks:
    - name: 1. Instalar dependencias base
      apt:
        update_cache: yes
        name: [git, curl, python3-pip, python3-docker, cockpit, openssl]

    - name: 2. Eliminar instalaciones previas de Mosquitto (Limpieza)
      shell: |
        sudo systemctl stop mosquitto || true
        sudo apt-get purge --auto-remove -y mosquitto mosquitto-clients || true
        sudo rm -rf /etc/mosquitto /var/lib/mosquitto /var/log/mosquitto
      ignore_errors: yes

    - name: 3. Asegurar directorio de trabajo
      file:
        path: "{{ base_path }}"
        state: directory
        owner: "{{ user_name }}"
        group: docker
        mode: '0775'

    - name: 4. Sincronizar archivos del repositorio a /opt/iot-stack
      copy:
        src: "./"
        dest: "{{ base_path }}"
        owner: "{{ user_name }}"
        group: docker
        mode: '0775'

    - name: 5. Generar Token único de InfluxDB
      shell: "openssl rand -hex 32"
      register: generated_token
      args:
        creates: "{{ influx_token_file }}"

    - name: 6. Crear archivo .env local
      copy:
        dest: "{{ influx_token_file }}"
        content: |
          INFLUXDB_TOKEN={{ generated_token.stdout | default('TOKEN_EXISTENTE') }}
          UID={{ ansible_user_uid }}
          GID={{ ansible_user_gid }}
        force: no

    - name: 7. Desplegar Portainer (Puerto 9443)
      docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        state: started
        restart_policy: always
        published_ports: ["9443:9443"]
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data

    - name: 8. Inicializar usuario vdc en Portainer
      uri:
        url: https://localhost:9443/api/users/admin/init
        method: POST
        body_format: json
        body:
          username: "{{ portainer_user }}"
          password: "{{ portainer_password }}"
        validate_certs: no
        status_code: [200, 409, 412]
      register: portainer_init
      until: portainer_init.status in [200, 409, 412]
      retries: 15
      delay: 5

    - name: 9. Obtener Token y Endpoint ID
      uri:
        url: https://localhost:9443/api/auth
        method: POST
        body: { "username": "{{ portainer_user }}", "password": "{{ portainer_password }}" }
        body_format: json
        validate_certs: no
      register: portainer_auth

    - name: 10. Desplegar Stack desde GitHub (Control Total)
      uri:
        url: "https://localhost:9443/api/stacks/create/standalone/repository?endpointId=1"
        method: POST
        headers: { "Authorization": "Bearer {{ portainer_auth.json.jwt }}" }
        body_format: json
        body:
          name: "iot-stack"
          repositoryURL: "{{ repo_url }}"
          composeFormat: "compose-v2"
          ComposeFilePathInRepository: "docker-compose.yml"
        validate_certs: no
        status_code: [200, 409]
